import type {
  ConfigurationAdapter,
  EngineConfiguration,
  EngineMcpServer,
  EngineSkill,
} from "../domain/engine-configuration.js";
import { HubError } from "../domain/errors.js";
import { canonicalJson, isStdioMcp } from "./manifest.js";
import type {
  ToolPackageCapabilities,
  ToolPackageConfiguration,
  ToolPackageManifest,
  ToolPackageRecord,
} from "./types.js";

/** Engine configuration limits from the engine schema (16 Skills, 16 MCP servers). */
export const ENGINE_LIMITS = Object.freeze({ skills: 16, mcpServers: 16 });

/**
 * What one installed package version contributes to an engine configuration.
 * Ownership is derived from the configuration itself, never from a second
 * binding registry: Skill paths and stdio MCP launch values contain the
 * content digest (`objects/<digest>`), and MCP names are `<id>-<name>`.
 * Matching on the digest survives relocation of the store root.
 */
export interface PackageFootprint {
  id: string;
  version: string;
  digest: string;
  status: ToolPackageRecord["status"];
  displayName: string;
  counts: { skills: number; mcp: number; cli: number };
  /** Lower-case engine MCP names generated by this version. */
  mcpNames: Set<string>;
  /** Remote endpoints by lower-case engine MCP name. */
  remote: Map<string, { type: "http" | "sse"; url: string }>;
}

export function footprint(
  record: ToolPackageRecord,
  manifest: ToolPackageManifest,
): PackageFootprint {
  const servers = manifest.mcpServers ?? [];
  const cli = manifest.cliTools ?? [];
  const names = servers.map((server) => `${manifest.id}-${server.name}`);
  if (cli.length) names.push(`${manifest.id}-cli`);
  return {
    id: record.id,
    version: record.version,
    digest: record.digest,
    status: record.status,
    displayName: manifest.displayName,
    counts: {
      skills: manifest.skills?.length ?? 0,
      mcp: servers.length,
      cli: cli.length,
    },
    mcpNames: new Set(names.map((name) => name.toLowerCase())),
    remote: new Map(
      servers.flatMap((server) =>
        isStdioMcp(server)
          ? []
          : [
              [
                `${manifest.id}-${server.name}`.toLowerCase(),
                { type: server.type, url: server.url },
              ] as const,
            ],
      ),
    ),
  };
}

export interface OwnedEntries {
  skills: EngineSkill[];
  mcpServers: EngineMcpServer[];
}

/** Entries of `configuration` that were generated by the given package version. */
export function ownedEntries(
  configuration: EngineConfiguration | undefined,
  owner: PackageFootprint,
): OwnedEntries {
  return {
    skills: (configuration?.skills ?? []).filter((skill) =>
      skill.path.includes(owner.digest),
    ),
    mcpServers: (configuration?.mcpServers ?? []).filter((server) => {
      const name = server.name.toLowerCase();
      if (!owner.mcpNames.has(name)) return false;
      if (server.type === "stdio")
        return canonicalJson({
          command: server.command ?? null,
          args: server.args ?? [],
          env: server.env ?? {},
        }).includes(owner.digest);
      const remote = owner.remote.get(name);
      return remote?.type === server.type && remote.url === server.url;
    }),
  };
}

export function isEmpty(entries: OwnedEntries): boolean {
  return !entries.skills.length && !entries.mcpServers.length;
}

/** Omits empty Skill/MCP arrays so unbinding restores the original shape. */
function compact(configuration: EngineConfiguration): EngineConfiguration {
  const { skills, mcpServers, ...rest } = configuration;
  return {
    ...rest,
    ...(skills?.length ? { skills } : {}),
    ...(mcpServers?.length ? { mcpServers } : {}),
  };
}

/** Removes exactly the given entries (by identity) and keeps everything else in order. */
export function withoutEntries(
  configuration: EngineConfiguration,
  entries: OwnedEntries,
): EngineConfiguration {
  const skills = new Set(entries.skills);
  const servers = new Set(entries.mcpServers);
  return compact({
    ...configuration,
    skills: (configuration.skills ?? []).filter((skill) => !skills.has(skill)),
    mcpServers: (configuration.mcpServers ?? []).filter(
      (server) => !servers.has(server),
    ),
  });
}

function conflict(code: string, message: string): HubError {
  return new HubError(code, message, 409);
}

function merge<T>(
  existing: T[],
  incoming: T[],
  key: (item: T) => string,
  label: "Skill" | "MCP server",
): T[] {
  const result = [...existing];
  for (const item of incoming) {
    const previous = result.find((candidate) => key(candidate) === key(item));
    if (!previous) result.push(item);
    else if (canonicalJson(previous) !== canonicalJson(item))
      throw conflict(
        "TOOL_PACKAGE_BIND_CONFLICT",
        `An existing ${label} ${key(item)} has different configuration and is not owned by this package`,
      );
  }
  return result;
}

export interface PlannedBinding {
  configuration: EngineConfiguration;
  /** Other versions of the same package whose entries were removed (replace). */
  replaced: string[];
}

/**
 * Plans the configuration after binding one package version. Entries already
 * owned by the same version are refreshed. Entries of other versions of the
 * same package id are removed only with `replace`; otherwise the engine keeps
 * one version per package and the plan fails with TOOL_PACKAGE_BIND_CONFLICT.
 * Entries not owned by the package are never removed, and name/path clashes
 * with them fail with TOOL_PACKAGE_BIND_CONFLICT. Exceeding the engine limits
 * fails with TOOL_PACKAGE_ENGINE_CAPACITY. Pure: nothing is persisted here.
 */
export function planBinding(
  configuration: EngineConfiguration | undefined,
  fallbackAdapter: ConfigurationAdapter,
  target: PackageFootprint,
  versions: readonly PackageFootprint[],
  fragment: ToolPackageConfiguration,
  replace: boolean,
): PlannedBinding {
  let next: EngineConfiguration = {
    ...configuration,
    adapter: configuration?.adapter ?? fallbackAdapter,
  };
  const replaced: string[] = [];
  for (const version of versions) {
    if (version.id !== target.id) continue;
    const owned = ownedEntries(next, version);
    if (isEmpty(owned)) continue;
    if (version.digest !== target.digest) {
      if (!replace)
        throw conflict(
          "TOOL_PACKAGE_BIND_CONFLICT",
          `This engine already uses ${version.id} ${version.version}; pass replace:true to switch to ${target.version}`,
        );
      replaced.push(version.version);
    }
    next = withoutEntries(next, owned);
  }
  next = compact({
    ...next,
    skills: merge(
      next.skills ?? [],
      fragment.skills,
      (skill) =>
        process.platform === "win32" ? skill.path.toLowerCase() : skill.path,
      "Skill",
    ),
    mcpServers: merge(
      next.mcpServers ?? [],
      fragment.mcpServers,
      (server) => server.name.toLowerCase(),
      "MCP server",
    ),
  });
  if (
    (next.skills?.length ?? 0) > ENGINE_LIMITS.skills ||
    (next.mcpServers?.length ?? 0) > ENGINE_LIMITS.mcpServers
  )
    throw conflict(
      "TOOL_PACKAGE_ENGINE_CAPACITY",
      `The engine would have ${next.skills?.length ?? 0} Skills and ${next.mcpServers?.length ?? 0} MCP servers; the limit is ${ENGINE_LIMITS.skills} each`,
    );
  return { configuration: next, replaced };
}

/** Capability names generated by a bind fragment, as returned by apply results. */
export function capabilities(
  fragment: ToolPackageConfiguration,
  manifest: ToolPackageManifest,
): ToolPackageCapabilities {
  return {
    skills: fragment.skills.map((skill) => skill.path),
    mcp: fragment.mcpServers.map((server) => server.name),
    cli: (manifest.cliTools ?? []).map((tool) => `cli_${tool.name}`),
  };
}
