#!/usr/bin/env node
// SPDX-License-Identifier: MIT
/**
 * Run the real-agent conformance suite and write its compatibility table.
 * Usage: node tools/conformance.mjs [--no-docs] (after pnpm build)
 *
 * Runs `node tools/run-tests.mjs conformance` (tests/conformance: real
 * agents wired by the daemon and run offline in a sandbox, see
 * tests/conformance/support.ts), collects each agent's row from the results
 * file the tests append to (HARNESSHUB_TEST_CONFORMANCE_RESULTS), and
 * replaces the generated block of docs/compatibility.md with the table:
 * agent, version, a column per item (chat, tools, stream, cancel, usage),
 * date, platform and what was observed. The text
 * around the block is kept. `--no-docs` prints the table instead. Exits
 * with the suite's status; the table is written either way, since a failing
 * agent is a row of it.
 */
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const DOCUMENT = path.join(ROOT, "docs", "compatibility.md");
export const BEGIN =
  "<!-- conformance:begin (generated by node tools/conformance.mjs) -->";
export const END = "<!-- conformance:end -->";

const ITEMS = ["tools", "stream", "cancel", "usage"];
const CHAT = {
  "wiring verified": "✓",
  "partially verified": "partial",
  blocked: "✗ blocked",
  "not installed": "not installed",
};
const RESULT = { pass: "✓", partial: "partial", fail: "✗", "not run": "not run" };

/**
 * The table of `rows` (parsed result lines), one per agent, in the order
 * they came: a column per item (chat is the row's status), and what was
 * observed: the reason, each item's detail and the notes.
 *
 * @param {Array<{agent: string, name: string, version: string, status: string, reason?: string,
 *   items?: Record<string, {result: string, detail?: string}>, notes: string[], date: string, platform: string}>} rows
 * @returns {string}
 */
export function renderTable(rows) {
  const cell = (text) => text.replaceAll("|", "\\|").replaceAll("\n", " ");
  const lines = [
    "| Agent | Version | Chat | Tools | Stream | Cancel | Usage | Date | Platform | Observed |",
    "|---|---|---|---|---|---|---|---|---|---|",
  ];
  for (const row of rows) {
    const items = ITEMS.map((name) => row.items?.[name]);
    const observed = [
      row.reason ? `chat: ${row.reason}` : "",
      ...ITEMS.map((name, index) =>
        items[index]?.detail ? `${name}: ${items[index].detail}` : "",
      ),
      ...row.notes,
    ].filter(Boolean);
    lines.push(
      `| ${[
        `${row.name} (\`${row.agent}\`)`,
        row.version,
        CHAT[row.status] ?? row.status,
        ...items.map((item) => (item ? (RESULT[item.result] ?? item.result) : "-")),
        row.date,
        row.platform,
        observed.join("; ") || "-",
      ]
        .map(cell)
        .join(" | ")} |`,
    );
  }
  return lines.join("\n");
}

/**
 * `document` with its generated block replaced by `table`.
 *
 * @throws {Error} When the document has no generated block.
 */
export function replaceBlock(document, table) {
  const start = document.indexOf(BEGIN);
  const end = document.indexOf(END);
  if (start < 0 || end < start)
    throw new Error(`docs/compatibility.md lacks the ${BEGIN} … ${END} block`);
  return `${document.slice(0, start + BEGIN.length)}\n\n${table}\n\n${document.slice(end)}`;
}

async function main(argv) {
  const docs = !argv.includes("--no-docs");
  const directory = await mkdtemp(
    path.join(os.tmpdir(), "hh-conformance-results-"),
  );
  try {
    const results = path.join(directory, "results.jsonl");
    await writeFile(results, "");
    const code = await new Promise((resolve, reject) => {
      const child = spawn(
        process.execPath,
        [path.join(ROOT, "tools", "run-tests.mjs"), "conformance"],
        {
          cwd: ROOT,
          env: { ...process.env, HARNESSHUB_TEST_CONFORMANCE_RESULTS: results },
          stdio: "inherit",
        },
      );
      child.once("error", reject);
      child.once("close", (exit) => resolve(exit ?? 1));
    });
    const rows = (await readFile(results, "utf8"))
      .split("\n")
      .filter(Boolean)
      .map((line) => JSON.parse(line));
    const table = renderTable(rows);
    if (!rows.length)
      process.stderr.write("conformance: no agent row was recorded\n");
    else if (docs) {
      await writeFile(
        DOCUMENT,
        replaceBlock(await readFile(DOCUMENT, "utf8"), table),
      );
      process.stdout.write(
        `conformance: wrote ${rows.length} rows to docs/compatibility.md\n`,
      );
    } else process.stdout.write(`${table}\n`);
    return rows.length ? code : 1;
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  process.exitCode = await main(process.argv.slice(2));
